[2020-07-22 09:57:12,791] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: MYSQLDAG.dbdump_in_minio 2020-07-21T00:00:00+00:00 [queued]>
[2020-07-22 09:57:12,803] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: MYSQLDAG.dbdump_in_minio 2020-07-21T00:00:00+00:00 [queued]>
[2020-07-22 09:57:12,803] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-07-22 09:57:12,804] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-07-22 09:57:12,804] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-07-22 09:57:12,986] {taskinstance.py:900} INFO - Executing <Task(BashOperator): dbdump_in_minio> on 2020-07-21T00:00:00+00:00
[2020-07-22 09:57:12,991] {standard_task_runner.py:53} INFO - Started process 24755 to run task
[2020-07-22 09:57:13,236] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: MYSQLDAG.dbdump_in_minio 2020-07-21T00:00:00+00:00 [running]> bhakti-Vostro-3558
[2020-07-22 09:57:13,256] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-07-22 09:57:13,258] {bash_operator.py:103} INFO - Temporary script location: /tmp/airflowtmpdht90jg5/dbdump_in_minioww1rxeqn
[2020-07-22 09:57:13,258] {bash_operator.py:115} INFO - Running command: #!/bin/bash -x
user=root
password=
dbname=airflow_db2
root_dir="/home/bhakti/airflow/"
location=$root_dir"input_data/dump_mysql_db.db"
if [ $dbname != " " ]
then
docker exec -it mysqlCon \
mysqldump --user $user --databases $dbname > $location
python3 $root_dir"minioconnect/minio_connection.py"
echo 'File uploaded successfully'
/opt/spark/bin/spark-submit airflow/config/settings.py
fi
[2020-07-22 09:57:13,267] {bash_operator.py:122} INFO - Output:
[2020-07-22 09:57:15,633] {bash_operator.py:126} INFO - mysqldump2020-07-22 09:57:15.632929.sql
[2020-07-22 09:57:16,091] {bash_operator.py:126} INFO - File uploaded successfully
[2020-07-22 09:57:17,800] {bash_operator.py:126} INFO - 20/07/22 09:57:17 WARN Utils: Your hostname, bhakti-Vostro-3558 resolves to a loopback address: 127.0.1.1; using 192.168.43.94 instead (on interface wlp6s0)
[2020-07-22 09:57:17,802] {bash_operator.py:126} INFO - 20/07/22 09:57:17 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2020-07-22 09:57:18,868] {bash_operator.py:126} INFO - 20/07/22 09:57:18 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2020-07-22 09:57:19,994] {bash_operator.py:126} INFO - python3: can't open file '/tmp/airflowtmpdht90jg5/airflow/config/settings.py': [Errno 2] No such file or directory
[2020-07-22 09:57:20,004] {bash_operator.py:126} INFO - log4j:WARN No appenders could be found for logger (org.apache.spark.util.ShutdownHookManager).
[2020-07-22 09:57:20,005] {bash_operator.py:126} INFO - log4j:WARN Please initialize the log4j system properly.
[2020-07-22 09:57:20,005] {bash_operator.py:126} INFO - log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[2020-07-22 09:57:20,100] {bash_operator.py:128} INFO - Command exited with return code 2
[2020-07-22 09:57:20,113] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-07-22 09:57:20,386] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-07-22 09:57:22,599] {logging_mixin.py:112} INFO - [2020-07-22 09:57:22,599] {local_task_job.py:103} INFO - Task exited with return code 1
