[2020-07-22 10:02:23,842] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: MYSQLDAG.dbdump_in_minio 2020-07-22T04:32:13.289020+00:00 [queued]>
[2020-07-22 10:02:23,856] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: MYSQLDAG.dbdump_in_minio 2020-07-22T04:32:13.289020+00:00 [queued]>
[2020-07-22 10:02:23,856] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-07-22 10:02:23,856] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-07-22 10:02:23,856] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-07-22 10:02:24,020] {taskinstance.py:900} INFO - Executing <Task(BashOperator): dbdump_in_minio> on 2020-07-22T04:32:13.289020+00:00
[2020-07-22 10:02:24,023] {standard_task_runner.py:53} INFO - Started process 32024 to run task
[2020-07-22 10:02:24,211] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: MYSQLDAG.dbdump_in_minio 2020-07-22T04:32:13.289020+00:00 [running]> bhakti-Vostro-3558
[2020-07-22 10:02:24,232] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-07-22 10:02:24,234] {bash_operator.py:103} INFO - Temporary script location: /tmp/airflowtmpsw8rfo_7/dbdump_in_minioj0sryedh
[2020-07-22 10:02:24,234] {bash_operator.py:115} INFO - Running command: #!/bin/bash -x
user=root
password=
dbname=airflow_db2
root_dir="/home/bhakti/airflow/"
location=$root_dir"input_data/dump_mysql_db.db"
if [ $dbname != " " ]
then
docker exec -it mysqlCon \
mysqldump --user $user --databases $dbname > $location
python3 $root_dir"minioconnect/minio_connection.py"
echo 'File uploaded successfully'
/opt/spark/bin/spark-submit "airflow/config/settings.py"
fi
[2020-07-22 10:02:24,243] {bash_operator.py:122} INFO - Output:
[2020-07-22 10:02:27,097] {bash_operator.py:126} INFO - mysqldump2020-07-22 10:02:27.096828.sql
[2020-07-22 10:02:27,315] {bash_operator.py:126} INFO - File uploaded successfully
[2020-07-22 10:02:29,585] {bash_operator.py:126} INFO - 20/07/22 10:02:29 WARN Utils: Your hostname, bhakti-Vostro-3558 resolves to a loopback address: 127.0.1.1; using 192.168.43.94 instead (on interface wlp6s0)
[2020-07-22 10:02:29,590] {bash_operator.py:126} INFO - 20/07/22 10:02:29 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2020-07-22 10:02:31,587] {bash_operator.py:126} INFO - 20/07/22 10:02:31 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2020-07-22 10:02:33,303] {bash_operator.py:126} INFO - python3: can't open file '/tmp/airflowtmpsw8rfo_7/airflow/config/settings.py': [Errno 2] No such file or directory
[2020-07-22 10:02:33,341] {bash_operator.py:126} INFO - log4j:WARN No appenders could be found for logger (org.apache.spark.util.ShutdownHookManager).
[2020-07-22 10:02:33,341] {bash_operator.py:126} INFO - log4j:WARN Please initialize the log4j system properly.
[2020-07-22 10:02:33,342] {bash_operator.py:126} INFO - log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[2020-07-22 10:02:33,399] {bash_operator.py:128} INFO - Command exited with return code 2
[2020-07-22 10:02:33,408] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-07-22 10:02:33,410] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-07-22 10:02:33,747] {logging_mixin.py:112} INFO - [2020-07-22 10:02:33,747] {local_task_job.py:103} INFO - Task exited with return code 1
