[2020-07-18 17:40:34,284] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: storing_data.db1_to_csv 2020-07-18T12:09:55.480162+00:00 [queued]>
[2020-07-18 17:40:34,294] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: storing_data.db1_to_csv 2020-07-18T12:09:55.480162+00:00 [queued]>
[2020-07-18 17:40:34,294] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-07-18 17:40:34,294] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-07-18 17:40:34,294] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-07-18 17:40:34,450] {taskinstance.py:900} INFO - Executing <Task(BashOperator): db1_to_csv> on 2020-07-18T12:09:55.480162+00:00
[2020-07-18 17:40:34,455] {standard_task_runner.py:53} INFO - Started process 192615 to run task
[2020-07-18 17:40:35,303] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: storing_data.db1_to_csv 2020-07-18T12:09:55.480162+00:00 [running]> bhakti-Vostro-3558
[2020-07-18 17:40:35,332] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-07-18 17:40:35,337] {bash_operator.py:103} INFO - Temporary script location: /tmp/airflowtmp62hqt5bj/db1_to_csvjutdxrvx
[2020-07-18 17:40:35,337] {bash_operator.py:115} INFO - Running command: #!/bin/bash -x
user=root
password=root
dbname=airflow_db1
docker exec -it mysqlCon \
mysql -D$dbname -p$password -u$user -e'SELECT * FROM employees INTO OUTFILE /input_files_mysql/sample1.csv FIELDS TERMINATED BY "," LINES TERMINATED BY "\n";'
[2020-07-18 17:40:35,350] {bash_operator.py:122} INFO - Output:
[2020-07-18 17:40:35,961] {bash_operator.py:126} INFO - mysql: [Warning] Using a password on the command line interface can be insecure.
[2020-07-18 17:40:35,967] {bash_operator.py:126} INFO - ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '/input_files_mysql/sample1.csv FIELDS TERMINATED BY "," LINES TERMINATED BY "\n"' at line 1
[2020-07-18 17:40:36,037] {bash_operator.py:128} INFO - Command exited with return code 1
[2020-07-18 17:40:36,052] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2020-07-18 17:40:36,056] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-07-18 17:40:44,130] {logging_mixin.py:112} INFO - [2020-07-18 17:40:44,130] {local_task_job.py:103} INFO - Task exited with return code 1
